/**
 * Chart export utilities: PNG, PDF, CSV, embed code, link copy.
 *
 * Uses html2canvas-pro for rasterization and jsPDF for PDF generation.
 * All exports are client-side — no backend round-trip needed.
 */

import html2canvas from "html2canvas-pro";
import { jsPDF } from "jspdf";

// ── PNG Export ──────────────────────────────────────────────────────────────────

export async function exportChartAsPng(
  chartElement: HTMLElement,
  filename = "MarketStats-Chart"
): Promise<void> {
  const canvas = await html2canvas(chartElement, {
    scale: 2, // retina quality
    backgroundColor: "#ffffff",
    useCORS: true,
    logging: false,
  });

  const link = document.createElement("a");
  link.download = `${filename}.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}

// ── PDF Export ──────────────────────────────────────────────────────────────────

export async function exportChartAsPdf(
  chartElement: HTMLElement,
  {
    filename = "MarketStats-Report",
    title = "Market Statistics",
    subtitle = "",
  }: {
    filename?: string;
    title?: string;
    subtitle?: string;
  } = {}
): Promise<void> {
  const canvas = await html2canvas(chartElement, {
    scale: 2,
    backgroundColor: "#ffffff",
    useCORS: true,
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  // Landscape A4 for wide charts
  const pdf = new jsPDF({
    orientation: imgWidth > imgHeight ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 12;

  // ── Header: gold accent bar + title ──
  pdf.setFillColor(218, 170, 0); // #DAAA00
  pdf.rect(0, 0, pageWidth, 2, "F");

  let yPos = 14;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.setTextColor(24, 24, 24); // #181818
  pdf.text(title, margin, yPos);

  if (subtitle) {
    yPos += 7;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(83, 85, 90); // #53555A
    pdf.text(subtitle, margin, yPos);
  }

  yPos += 6;

  // ── Chart image ──
  const availableWidth = pageWidth - margin * 2;
  const availableHeight = pageHeight - yPos - 18; // leave room for footer
  const ratio = Math.min(
    availableWidth / imgWidth,
    availableHeight / imgHeight
  );
  const drawWidth = imgWidth * ratio;
  const drawHeight = imgHeight * ratio;

  pdf.addImage(imgData, "PNG", margin, yPos, drawWidth, drawHeight);

  // ── Footer ──
  const footerY = pageHeight - 8;
  pdf.setFontSize(7);
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated by MarketStats | certihomes.com | ${new Date().toLocaleDateString()}`,
    margin,
    footerY
  );

  // Gold bottom bar
  pdf.setFillColor(218, 170, 0);
  pdf.rect(0, pageHeight - 2, pageWidth, 2, "F");

  pdf.save(`${filename}.pdf`);
}

// ── CSV Export ──────────────────────────────────────────────────────────────────

export interface CsvRow {
  month: string;
  [areaName: string]: string | number | null;
}

export function exportChartAsCsv(
  pivotedData: CsvRow[],
  metricLabel: string,
  filename = "MarketStats-Data"
): void {
  if (pivotedData.length === 0) return;

  const headers = Object.keys(pivotedData[0]);
  const rows = pivotedData.map((row) =>
    headers.map((h) => {
      const val = row[h];
      if (val === null || val === undefined) return "";
      if (typeof val === "string" && val.includes(",")) return `"${val}"`;
      return String(val);
    })
  );

  const csvContent = [headers.join(","), ...rows.map((r) => r.join(","))].join(
    "\n"
  );
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}-${metricLabel.replace(/\s+/g, "_")}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}

// ── Embed Code ──────────────────────────────────────────────────────────────────

export function generateEmbedCode(embedUrl: string): string {
  return `<iframe
  src="${embedUrl}"
  width="100%"
  height="520"
  frameborder="0"
  style="border: 1px solid #D9D8D6; border-radius: 8px;"
  title="MarketStats Chart"
  loading="lazy"
></iframe>`;
}

// ── Copy Link ───────────────────────────────────────────────────────────────────

export async function copyCurrentLink(): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(window.location.href);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement("textarea");
    textarea.value = window.location.href;
    textarea.style.position = "fixed";
    textarea.style.opacity = "0";
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
    return true;
  }
}
